### ISSUE TITLE
Do you have any plans to update device list?

### ISSUE THREAD

**Issue by ma3tk** [openstf/stf-device-db#2]
Hi.
I need some new devices information on OpenSTF, but currently this repository is not updated almost 4months.
Do you have any plans to update device list?

**Comment by gunta** [comment]
Sorry for the delay, updated now. The problem is that updating the db is currently a very manual time consuming process, we are thinking on ways to change this.

Is there any particular device which is not yet in the database that you're currently using?

**Comment by Ashraf-Ali-aa** [comment]
@gunta can you add this to the database it is a Tesco Hudl 2.

```
{ serial: '131114PE5089152',
  platform: 'Android',
  manufacturer: 'PEGATRON',
  operator: null,
  model: ' Hudl 2',
  version: '4.4.2',
  abi: 'x86',
  sdk: '19',
  product: 'HTF8A4XX',
  display:
   { id: 0,
     width: 1200,
     height: 1920,
     xdpi: 273.97698974609375,
     ydpi: 274.593994140625,
     fps: 60.000003814697266,
     density: 2,
     rotation: 90,
     secure: true,
     size: 8.250686348779125,
     url: 'ws://10.241.88.15:7400' },
  phone: { network: 'UNKNOWN' } }
```
